language: java
jdk: oraclejdk8

sudo: required

services:
- docker

env:
  global:
    travis encrypt DOCKER_USER=”dockerhub-username-test”
    travis encrypt DOCKER_PASS=”dockerhub-password”

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- export IMAGE_NAME=sivaprasadreddy/freelancerkit
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME