language: java
jdk: oraclejdk8
sudo: required
services:
- docker
env:
  global:
  - secure: d9XzMD8+3C7X+xZddkC4rZc1aGk8jPTSVW+tmtssg1a1gSSgMCttpe339jrRb//gi4W9kfGyuBgGhq4qms7IGg1cz0xsIV6aV0P8tkSCCRkKqXB24DTksSEzpqSj7fi1fH/ksS6+c0L5orz8WtNCkXf1FRdv6opR1eCoFLTreCu8DgtLKIvSUtweYLKwVGmsmeVHXiZLb+x2h8yP5L7fLmH9q54eIFUNwP1TRvnEhTkI5IiDNkHbXgf5f92y5Zhxjc9x1DmM1bWGYKBdFj8WMhSDeVsx8dFNATwKNwCuraOgwQWvsCtdkJezuO4UPs6OM9G2HKV4cW3Nkdt1wiiW0YVQfVwRmviqVs3AznnUyf+4Hi1N+KmaXANGQ+KqwzsgnnMQwGX8SfZYPUTv0iIj+ht9x9eT3tFG9dX5bVV8M957KLDcbc8yYUkegRqgE6hCKZ34uupck759uluMVCT4j1YJ3JEPqwZ936ElhSEm2cbbsVt3vJdB08xEUUoOmqEa+jxpii/YOaHriLezffSZicN7Hzm5f+fuKz1oMcEMvaXfFx5w9x8lBxWs3+5DvOjt3txE9uGlx6D8A6J9psYs3uxu9bVaR4YkX1UiW8PqHE40uR1icKvX1KJU3kqd9AHeTBoPn2VvmB3pLkcZnO4GMFRqi74rqBTXrfpfM2BR1Ms=
  - secure: ocr1CKMDUDoavrJXMrAfaJinn7oo0p3GDc9FTFuQzyVlS/2HTc7ymX15Bb3MpynoZFVgd7QlmR+wIGEZNbv5Deg/QcQt0XE546FKcbxasD90DptIQBUjNNFqk518V9Cij7nba2zWjXrhjjH4c1jtoheOnNqJ/BrszLVP5L0PQtxUZms2tsj9BT9nCF+RQIo7uKjF8C0RWm9PUfkgaBUId0f7LzERgrgerB4NzM+o/o/b6IZ8H9Ky4QyMikK1pv6hfZSC6KAyblh38C5Cdm7q29k7EzsZibiX30Kom7kNjuTZ7q5q79pmnQaaovn2R1pPaySOjI8Gq2jpVArWW0DQbYYZMyGTmUfTCZbaS7u9v2ODsR2QSVsklYcCZ6FKPesrCSTzXbyY8qt+ztkS0e7H0lGJf+ZBCBGm1Zect3yh8P3SUJr7ZUJ5a8Yhrma7qHLkLapvni0vJAlBkE75Z46TlIkGpR4r5Nqip1tPuxY1lPV6Rh/L+jAD7C9BQsedx4PUciJ5m7jqd+K54p7TmCyTyRgV42FXZ9zSZ5Ry1tALqYZZBhT0W50pERODgqNS6ZtChynD0hSMsT9rQ+gXjvdCbkxsEutHdFYOUSCKBakS+ymetcmkGlfxkR3IDYjmgjZ8oZfNhzTi1Z1ZqaouZAm2F+281z2IjapbCYLWdXYPZ0A=
  - COMMIT=${TRAVIS_COMMIT::7}
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG='if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi'
- export IMAGE_NAME=mfouche/mikesite
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME