language: java
jdk: oraclejdk8
sudo: required
services:
- docker
env:
  global:
  - secure: oY6q5bEt8EzK8Jq16DhE6NCuHLfEsRaB1mTBq0mvVtD+dWl3KmBhsMTOF4/OmddvWe+aInJS7uMcnfA2Zj9t3awyFaHKDlG3/6ZNam3iUT4rr3tOE/ZWsvIG78qCd3zyPOEARrOprFvi6423hd2BdZ6CTlGRSOwmmX3GKfpWdYHOc0rzTVPSFjBpTp6a61IEr1we8AOHmVbKj2c5I1FyxKimAToPkCVYjraDO3Eb1ReVANNOLvPbzGISRp3GpWXMYsCDpoXqemnwJl1oe0hOAB+LsdWGqCtKC8azNsymfCxQEGGWanl2OIEw971QT0WqsuiJ76l+sobddE0X8oKCYLdDSt8i5z0SmneyiVxwhu49qqehR/H0MpJwbDcbo8bEDOVNcfzu/uNblNcAJ4kzQWArmO36TOWGblpsUvNQqAUigT4NItEwdLBPZAVwjmQsawAI++0gVSmgbrXgzDozbz9rvQjbYuocRUrlpxI9z9FjHPNXqb7XIaC20J0a9j/FDVyqhRPucscYSSJCs7zBn2NV7ElqAmgMJZdNyad4RNKZtF4pzcZz/q0dCv091M5y6qmxc60HeHMAT5po6vkqc8DprlTCoiToCNghlhxo3nhSPLI08YJDXpztyy0nSZHQUOPw/7besYG/vT0mKghS53AO+o2tL5x3bi/hzJtAWew=
  - secure: Olghhlq95Mb7NGNhGdee9BKQhExFqPaCgyRqxSg6NqD7KBVtrCxMe5yooxLJvyB91OQ8FHa/NrsqXaX2Xs99d7zTJtpfORFJpmuAzTKdzJQubqEyy1fnSm5xXLDwxrVOpUM57hwTybMUyb+vHnxNKQMp1GLESj3MjEaGPA1bO3KYLgMbvebFfeb/jlm5rQMbBwovs05NBDcLw2Tp6+3QBUetcBwVF6h3O2d140Bejuv/2DXZERjKNOll8VPbPplqu+IECcVGC5ZB+K8Y2rUxswaGIk7Z5ku1ixBVU1wag2ywUrCE/zT2IDtfQvHbyqSaiZ7DA3DUQNwFwq1NRAAwKF4RotHvdEqIAoZr0t5388Qm7xiBIcWYyXylzCfruT9hmfDi7GbWqNjZydal3SaorF/fHyew15Oujois/QuZ9ybGC7PYfyR7dR7HsVcB3alJ85nfX9akvGbMwh8+kHSzRIgEFdE5ueADHlLmO9iIT4j++9oERRVbZdubOqziRhlAEAwspTF0IVwFB+z4RgmtI88+Bt0ruHfhI1GudVgkPu+Mg2TGbyD0vJWaHsFyDlCSuXK4XYaoQeq+h1chTrbnED45RqjgQuArpVZu1RIL0vQFYyMdoJWRIaQJZ0HFgEdO7TH/bDwh29jDPvpsNvSJpekQdOIT7seOyvV9Z4ogrKo=
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG='if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi'
- export IMAGE_NAME=MichaelFouche/mikesite
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME