language: java
jdk: oraclejdk8

sudo: required

services:
- docker

env:
  global:
  - secure: oY6q5bEt8EzK8Jq16DhE6NCuHLfEsRaB1mTBq0mvVtD+dWl3KmBhsMTOF4/OmddvWe+aInJS7uMcnfA2Zj9t3awyFaHKDlG3/6ZNam3iUT4rr3tOE/ZWsvIG78qCd3zyPOEARrOprFvi6423hd2BdZ6CTlGRSOwmmX3GKfpWdYHOc0rzTVPSFjBpTp6a61IEr1we8AOHmVbKj2c5I1FyxKimAToPkCVYjraDO3Eb1ReVANNOLvPbzGISRp3GpWXMYsCDpoXqemnwJl1oe0hOAB+LsdWGqCtKC8azNsymfCxQEGGWanl2OIEw971QT0WqsuiJ76l+sobddE0X8oKCYLdDSt8i5z0SmneyiVxwhu49qqehR/H0MpJwbDcbo8bEDOVNcfzu/uNblNcAJ4kzQWArmO36TOWGblpsUvNQqAUigT4NItEwdLBPZAVwjmQsawAI++0gVSmgbrXgzDozbz9rvQjbYuocRUrlpxI9z9FjHPNXqb7XIaC20J0a9j/FDVyqhRPucscYSSJCs7zBn2NV7ElqAmgMJZdNyad4RNKZtF4pzcZz/q0dCv091M5y6qmxc60HeHMAT5po6vkqc8DprlTCoiToCNghlhxo3nhSPLI08YJDXpztyy0nSZHQUOPw/7besYG/vT0mKghS53AO+o2tL5x3bi/hzJtAWew=
  - secure: FxBhbKVT/B0fpQMpDY7Q/tMoczPqP4UqraGfzpe7a55UwbgoibrxFb/jqZ4uLARmseXJfNDRlHSaGK8HqyyUu5JYhXJDH1bpkROCqOPJoBYADOqmAKUxK2PJSYenaFNZd0aHIYhZOUgk9FaZAke2Lm2bPVe5E+v9SGHXNmTmYSPLBqxIVDa3/I/kWAqA6gTfqsea/ovDa7PjQhjWlM7mdCdUq+VqCxhmQpNF8CFtdq7RW/OUHjHkXRuA6tkcUXSVwO7VPe4IylE1Z1ebNV4AxvoZ5+qs+GBtv6xsuWUpnzjQ+qcFhoZvYZ++0ekxyb7e7tmfy7XLVBJgWGohntMFx3zNE1FRBj8EeGQyTq4AUISs0OW3eZe970zNl7aCdquzQ6ZNtwVYxsH8OMA6cB6pVRNndqRRPILjBWUxbKzG5FSvzX+HqkPsLYId4W3bL+StZe5gKppjGkqK2t+MLRnCr1B8YuQrPirzNXzC+HLsWUFnDikYGBIYjXENR0kyNjZQCDDmgrNvq9paGeFOLHfw8GQs6ZzOZAagp73WAGmy58Tr+rHyGlaEow48ZOTwC4Yy/xgRiw82FGyjVDC99SW1C+hlF7kH3803wmhel+woHV6kI3GMrzkkOHO9+g7yJwOJEUkL0bW8rM6xLA4Ct9NeswWeZ1P++YqxIosSk3dHndg=
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG='if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi'
- export IMAGE_NAME=sivaprasadreddy/freelancerkit
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME